<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>RyzeAuth.EcosystemTester</AssemblyName>
    <RootNamespace>RyzeAuth.EcosystemTester</RootNamespace>
  </PropertyGroup>
</Project>
